gcreds: output fixes to function update_awscli

diff --git a/gcreds b/gcreds
--- a/gcreds
+++ b/gcreds
@@ -38,10 +38,10 @@ purple=$(tput setaf 5)
 red=$(tput setaf 1)
 white=$(tput setaf 7)
 yellow=$(tput setaf 3)
-orange='\\033[38;5;95;38;5;214'
+orange='\033[38;5;95;38;5;214m'
 gray=$(tput setaf 008)
-lgray='\033[0;37m'    # light gray
-dgray='\033[1;30m'    # dark gray
+lgray='\033[38;5;95;38;5;245m'    # light gray
+dgray='\033[38;5;95;38;5;8m'      # dark gray
 reset=$(tput sgr0)
 #
 BOLD=`tput bold`
@@ -168,7 +168,7 @@ function std_message(){
     shift
     pref="----"
     if [[ $1 ]]; then
-        pref="${1:0:4}"
+        pref="${1:0:5}"
         shift
     fi
     echo -e "\n${yellow}[ $cyan$pref$yellow ]$reset  $msg\n" | indent04
@@ -176,8 +176,8 @@ function std_message(){
 
 function std_error(){
     local msg="$1"
-    std_logger "[EROR]: $msg"
-    echo -e "\n${yellow}[ ${red}EROR${yellow} ]$reset  $msg\n" | indent04
+    std_logger "[ERROR]: $msg"
+    echo -e "\n${yellow}[ ${red}ERROR${yellow} ]$reset  $msg\n" | indent04
 }
 
 function std_warn(){
@@ -567,14 +567,20 @@ function gcreds_remove_creds(){
     # log out start
     std_logger "[INFO]: Attempting to remove temp credentials from local config"
     # header
-    echo -e "\n--${accent}${BOLD} CLEARING LOCAL CONFIG ${UNBOLD}${reset}--\n" | indent10
-    echo -e "All temp credentials from your local config will be discarded." | indent02
-    echo -e "Your local awscli config will be returned to previous (clean) state.\n" | indent02
+    cat<<EOM
+
+                        --${accent}${BOLD} CLEARING LOCAL CONFIG ${UNBOLD}${reset}--
+
+    All temporary credentials generated by $pkg in your local config
+    will be discarded. Your local awscli config will be returned to
+    its previous (clean) state.
+
+EOM
     if [ $silent ]; then
         # clean config, no user input
         CHOICE="y"
     else
-        read -p "  ${yellow}Purge existing temporary credentials?${reset} [y]:  " CHOICE
+        read -p "  ${yellow}  Purge existing temporary credentials?${reset} [y]:  " CHOICE
     fi
     if [[ -z "$CHOICE" ]] || [[ "$CHOICE" == "y" ]] || [[ "$CHOICE" == "yes" ]]; then
         # restore clean config from backup
@@ -735,7 +741,7 @@ function gcreds_update_expiration(){
     #       2 = expire expiration, but keep config files (not used)
     local state=$1
     #
-    if [ $1 == 0 ] && [ -e $config_path/credential* ]; then
+    if [ $1 == 0 ] && [ -e $config_path/credential.expiration ]; then
         rm $config_path/credential.*
         std_logger "[INFO]: Credential expiration values cleared"
     elif [[ $1 == 1 ]]; then
@@ -910,13 +916,13 @@ gcreds_monitor(){
 
 function update_awscli(){
     ## update local awscli iam user credentials ##
-    local choice
-    local profile
+    local choice                      # user selection
+    local profile                     # valid profile in local awscli config
     local awscli_bin=$(which aws)     # aws binary
     local clear_bin=$(which clear)    # clear screen bin file
-    local valid
+    local valid=0                     # loop counter
     #
-    $clear_bin         # clear screen
+    $clear_bin                        # clear screen
     cat<<EOM
 
                           ${BOLD}${accent}awscli${reset}${UNBOLD} update
@@ -932,14 +938,13 @@ function update_awscli(){
     Type ${yellow}'y'${reset} when you are ready to begin. Hit ${yellow}'return'${reset} to quit.
 
 EOM
-    read -p "${yellow}    Continue? [quit]${reset} " choice
+    read -p "${yellow}    Continue? [quit]:${reset} " choice
     if [ -z $choice ] || [ $choice == 'quit' ]; then
         echo -e '\n'
         exit 0
     fi
-    if gcreds_preexisting_creds; then
-        gcreds_remove_creds -s
-    else
+    # check if temp credentials; if yes, clear them
+    if ! gcreds_preexisting_creds; then
         std_message "No temporary credentials found in your local config" INFO
     fi
     valid=0
@@ -947,7 +952,7 @@ EOM
         echo -e '\n  What is the iam username associated with the awscli profile' | indent02
         echo -e '  you wish to update?  If you wish to update the default profile' | indent02
         echo -e '  hit return.\n' | indent02
-        read -p "${yellow}    iam username to update: [default] ${reset}" choice
+        read -p "${yellow}    iam username to update [default]: ${reset}" choice
         echo -e '\n'
 
         if [ -z $choice ]; then
@@ -958,18 +963,19 @@ EOM
         # validate username in local config
         key=$(aws configure get "$profile".aws_access_key_id)
         if [ ! $key ]; then
-            std_message "Profile name ($profile) not in your local config. " EROR
+            std_message "Profile name ($profile) not in your local config. " ERROR
         else
             valid=1
         fi
     done
-
+    echo -e "\nUpdating credentials for iam user: ${red}${BOLD}$profile${UNBOLD}:"${orange}"\n"
     if [ $profile == 'default' ]; then
         $awscli_bin configure
     else
         $awscli_bin configure --profile $profile
     fi
-    std_message "awscli configuration update complete" INFO
+    # print footer
+    std_message "${reset}awscli configuration update complete" INFO
     #
     # <-- end function update_awscli -->
 }
@@ -1027,3 +1033,4 @@ rm $config_path/.session.profile $config_path/token.*
 #<-- end MAIN -----------------------------------------------------------------
 #
 exit 0
+/home/blake/.aws/credentials
